### ISSUE TITLE
Generate from new ecore with Instances

### ISSUE THREAD

**Issue by filippomc** [openworm/org.geppetto.python#44]
Ecore file: https://github.com/openworm/org.geppetto.model/blob/feature/30/src/main/resources/geppettoModel.ecore

**Comment by aranega** [comment]
Hi @filippomc , I came accross the issue and I was re-reading the `README`, regarding the code generation, the use of the Acceleo generator is not mandatory anymore if the python version is >= 3.5, instead, it would be prefereable to use `pyecoregen` which is more up to date and which is easier to use and better to deal with. If you want, there is also the `setuptools-pyecore` plugin that allows you to integrate a `generate` command to your `setup.py` for easier integration. 
Of course, it's not mandatory, but I think it would ease further code generation ;)

**Comment by filippomc** [comment]
I @aranega thanks for the advice! I remember I checked that when I rebuilt the first time, probably I stumbled first on a clear Acceleo tutorial and that's why. Do you think it's worth to redo that with pycoregen also now that is merged? We have a bunch of manual changes there so the merge is quite annoying at this time

**Comment by aranega** [comment]
I don't think there would have a lot of changes for those version with the current state of the metamodel (not sure though), but it should be fine. 
I had started a small tool on the side quite a time ago for pygeppetto to generate a new version easily in order to produce the new version of the code, but perhaps a modified version of pyecoregen for pygeppetto could be interesting in order to directly reflect the manual changes you introduced (of course, not for this version, but for the next one).

**Comment by filippomc** [comment]
That would be great. Other than a few import errors that have to be fixed every time, we are basically implementing methods that were not implemented, probably it would be easy I think to introduce that on the pipeline. 
More though could be with that change for timeseries you introduced to fix the problem with sets: https://github.com/openworm/pygeppetto/blob/d0677a76c1cef64798bca50674cffd6c4b92d7fd/pygeppetto/model/values/values.py#L155
Is it even needed with new pyecore version?

**Comment by aranega** [comment]
Unfortunately, it is still needed. I have some ideas about how to reduce computation time without having to manually introduce these things, but it will imply huge refactoring. The other solution is to introduce a custom generation for those cases. It can be detected during code generation, so it could work!

**Comment by filippomc** [comment]
Hi @aranega I tried to regenerate with pyecoregen and I get this error:

```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/resource.py", line 454, in _try_resource_autoload
    resource = rset.get_resource(external_uri)
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/resource.py", line 90, in get_resource
    resource.load(options=options)
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/xmi.py", line 30, in load
    tree = parse(self.uri.create_instream())
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/resource.py", line 210, in create_instream
    self.__stream = urllib.request.urlopen(self.plain)
  File "/opt/conda/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/pyecoregen", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/pyecoregen/cli.py", line 15, in main
    generate_from_cli(sys.argv[1:])  # nocover
  File "/opt/conda/lib/python3.7/site-packages/pyecoregen/cli.py", line 62, in generate_from_cli
    ).generate(model, parsed_args.out_folder)
  File "/opt/conda/lib/python3.7/site-packages/pyecoregen/ecore.py", line 330, in generate
    super().generate(model, outfolder)
  File "/opt/conda/lib/python3.7/site-packages/multigen/generator.py", line 39, in generate
    task.run(element, outfolder)
  File "/opt/conda/lib/python3.7/site-packages/multigen/generator.py", line 65, in run
    self.generate_file(element, filepath)
  File "/opt/conda/lib/python3.7/site-packages/multigen/jinja.py", line 43, in generate_file
    context = self.create_template_context(element=element)
  File "/opt/conda/lib/python3.7/site-packages/pyecoregen/ecore.py", line 118, in create_template_context
    imported_classifiers=self.imported_classifiers(element)
  File "/opt/conda/lib/python3.7/site-packages/pyecoregen/ecore.py", line 96, in imported_classifiers
    imported |= {t for t in attributes_types if t.ePackage not in {p, ecore.eClass, None}}
  File "/opt/conda/lib/python3.7/site-packages/pyecoregen/ecore.py", line 96, in <setcomp>
    imported |= {t for t in attributes_types if t.ePackage not in {p, ecore.eClass, None}}
  File "/opt/conda/lib/python3.7/site-packages/pyecore/ecore.py", line 968, in __getattribute__
    decoded = resource.resolve_object(self._proxy_path)
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/resource.py", line 390, in resolve_object
    decoder = self._get_href_decoder(newpath, path)
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/resource.py", line 443, in _get_href_decoder
    decoder = self._try_resource_autoload(uri, original_uri)
  File "/opt/conda/lib/python3.7/site-packages/pyecore/resources/resource.py", line 460, in _try_resource_autoload
    .format(uri))
TypeError: Resource "http://www.eclipse.org/emf/2003/XMLType" cannot be resolved
```
The command I used is `pyecoregen -vv -e geppettoModel.ecore -o ~/pygeppetto_new`
The same ecore file generates correctly with Acceleo.
Do you think I missed something?

**Comment by aranega** [comment]
Ah, that's because the geppetto ecore file is using XML types and they are not registered by default by pyecore (if I'm not mistaken), I'll check tomorrow about that and I'll write a simple script to generate everything using pyecoregen. I know also there is a way or registering metamodels through command line, but I don't remember how.

**Comment by aranega** [comment]
@filippomc I tried quickly this morning, indeed, the problem came from unregistered XML types
Here is the small script I used to generate the metamodel on my machine
```python
from pyecore.resources import ResourceSet
from pyecoregen.ecore import EcoreGenerator
import pyecore.type  # We register the XML types (generated by pyecoregen)

# We open the metamodel
rset = ResourceSet()
mm_root = rset.get_resource('pygeppetto/ecore/geppettoModel.ecore').contents[0]

# We generate the code using the EcoreGenerator
EcoreGenerator(auto_register_package=True).generate(mm_root, outfolder='new_mm')
```
This script could be enhanced with dedicated templates for the project, that would avoid you to have to manually perform some modifications after (about collections for example).

By the way, I never understood so much why XML types are used here, all the types in the metamodel could be simple ecore types (only String, Boolean, Long, Double and Int are used, you could find equivalent types in ecore)?

**Comment by filippomc** [comment]
thanks @aranega, that works and it is much easier than acceleo! 
@tarelli what about adding the script into the pygeppetto source base?

**Comment by aranega** [comment]
@filippomc A good thing is that if pygeppetto code needs some specific tweak, dedicated templates could be produced (it requires a little bit of work, but it's really doable).

**Comment by tarelli** [comment]
@filippomc if it makes the generation easier why not
